# Generated by Django 5.1.2 on 2024-11-21 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_feedback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('party_one_name', models.CharField(max_length=255)),
                ('party_one_role', models.CharField(blank=True, max_length=255, null=True)),
                ('party_two_name', models.CharField(max_length=255)),
                ('party_two_role', models.CharField(blank=True, max_length=255, null=True)),
                ('effective_date', models.DateField()),
                ('purpose', models.TextField()),
                ('obligations', models.TextField()),
                ('payment_terms', models.TextField(blank=True, null=True)),
                ('duration', models.CharField(blank=True, max_length=255, null=True)),
                ('termination_clause', models.TextField(blank=True, null=True)),
                ('confidentiality_clause', models.TextField(blank=True, null=True)),
                ('dispute_resolution', models.TextField(blank=True, null=True)),
                ('penalties_for_breach', models.TextField(blank=True, null=True)),
                ('notary_required', models.BooleanField(default=False)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='contract_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
