# Generated by Django 5.1.2 on 2024-11-23 00:22

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contractsteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsteps',
            name='confidentiality_clause',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='dispute_resolution',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='obligations',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='payment_terms',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='penalties_for_breach',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='purpose',
            field=tinymce.models.HTMLField(),
        ),
    ]
