# Generated by Django 5.1.2 on 2024-11-23 19:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_contractsteps_confidentiality_clause_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsteps',
            name='effective_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='obligations',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='party_one_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='party_two_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contractsteps',
            name='purpose',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
