# Generated by Django 5.1.2 on 2024-11-23 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_contractsteps_effective_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsteps',
            name='attachments',
        ),
    ]
