# Generated by Django 5.1.2 on 2024-11-26 17:44

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_contractsteps_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractsteps',
            name='termination_clause',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
