# Generated by Django 5.1.2 on 2024-12-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_validationresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproject',
            name='contract_steps',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_project', to='api.contractsteps'),
        ),
    ]
