# Generated by Django 5.1.2 on 2024-12-09 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contractproject_contract_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproject',
            name='check_completed',
            field=models.BooleanField(default=False),
        ),
    ]
