# Generated by Django 5.1.2 on 2024-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_contractproject_check_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsteps',
            name='check_completed',
            field=models.BooleanField(default=False),
        ),
    ]
