# Generated by Django 5.1.2 on 2024-12-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_contractsteps_check_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractproject',
            name='has_changes',
            field=models.BooleanField(default=False),
        ),
    ]
