# Generated by Django 5.1.2 on 2024-12-12 01:08

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contractproject_has_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractsteps',
            name='notarization',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
