# Generated by Django 5.1.2 on 2024-12-15 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_contractsteps_confidentiality_clause_required_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractsteps',
            name='confidentiality_clause_required',
        ),
        migrations.RemoveField(
            model_name='contractsteps',
            name='dispute_resolution_required',
        ),
        migrations.RemoveField(
            model_name='contractsteps',
            name='penalties_for_breach_required',
        ),
    ]
