# Generated by Django 5.1.2 on 2024-12-26 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
