# Generated by Django 5.1.2 on 2025-01-07 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_paymentrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationresult',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='api.contractsteps'),
        ),
    ]
