# Generated by Django 5.1.2 on 2025-01-09 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_validationresult_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationresult',
            name='contract_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='api.contractproject'),
        ),
        migrations.AlterField(
            model_name='validationresult',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='api.contractsteps'),
        ),
    ]
